### ISSUE TITLE
Scaling with x=1

### ISSUE THREAD

**Issue by nattyluke** [thednp/dommatrix#3]
I dont know why scaling like `scale(x,y)` is only allowed for `x!==1`. It should be possible to do `scale(1,-1)` for example which leads to an error.
So line 287 in index.ts  should be:  `prop === "scale" && !Number.isNaN(x) && z === undefined`

**Comment by thednp** [comment]
Please create a reproducible example.

**Comment by nattyluke** [comment]
```ts
import CSSMatrix from '@thednp/dommatrix';

const matrix = new CSSMatrix('scale(1, -1)');

expect(matrix.toString()).toBe('matrix(1, 0, 0, -1, 0, 0)');

const matrix2 = new CSSMatrix('scale(2, -1)');
expect(matrix2.toString()).toBe('matrix(2, 0, 0, -1, 0, 0)');
```
1st test: TypeError: CSSMatrix: invalid transform string
2nd test: runs fine

**Comment by thednp** [comment]
Thank you. Will look into it and provide a fix asap. Will need you to confirm, so will tag you here.

**Comment by thednp** [comment]
@nattyluke please run `pnpm install github:thednp/dommatrix` give it a test and confirm or provide feedback. I've updated the tests to test the fix as well.

Note: I remember the reason why we need to check `x !== 1` or `y !== 1` equality is because some complex stuff like SVG path commands require a very strict number checking, so I have to test this on [SVGPathCommander](https://github.com/thednp/svg-path-commander) as well.

A few minutes later, I can confirm the fix is OK for me, I've published v2.0.11.

**Comment by nattyluke** [comment]
Thanks, the fix is working for me!
I still dont see any reason why
```typescript
const matrix = new CSSMatrix('scale(1, 1)');
expect(matrix.toString()).toBe('matrix(1, 0, 0, 1, 0, 0)');
```
is forbidden.
https://developer.mozilla.org/de/docs/Web/CSS/transform-function/scale tells me nothing about it.

**Comment by thednp** [comment]
It's not forbidden, it's to be avoided since it produces no effect, multiplication of 16x16 matrix is not exactly 1+1.
